name: Build Raspberry Pi Sensor Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build project
      run: make all

    - name: Run executable (optional, mock only)
      run: |
        chmod +x sensor_hub
        ./sensor_hub || true  # allow mock runs to pass even if they fail
